# Generated by Django 2.0.2 on 2018-07-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibandapp', '0002_auto_20180707_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variants',
            field=models.ManyToManyField(blank=True, related_name='_product_variants_+', to='mibandapp.Product'),
        ),
    ]
