# Generated by Django 2.0.2 on 2018-07-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibandapp', '0003_auto_20180708_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiver_city',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_country',
            field=models.CharField(default='NG', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_email',
            field=models.EmailField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_first_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_last_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_phone',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_state',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_street',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
