# Generated by Django 2.0.2 on 2018-07-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibandapp', '0004_auto_20180708_0708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cookie_id',
            new_name='cart_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='items',
            new_name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
