# Generated by Django 2.0.2 on 2018-07-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mibandapp', '0005_auto_20180708_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='items',
        ),
    ]
