# Generated by Django 2.0.2 on 2018-07-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mibandapp', '0006_auto_20180708_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
