# Generated by Django 2.0.2 on 2018-07-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibandapp', '0007_remove_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_notes',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
