# Generated by Django 2.0.2 on 2018-07-10 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mibandapp', '0008_order_additional_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibandapp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=32)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='receiver_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='receiver_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='receiver_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='receiver_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='receiver_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='receiver_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='receiver_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='receiver_street',
            new_name='street',
        ),
    ]
