# Generated by Django 2.0.2 on 2018-07-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mibandapp', '0009_auto_20180710_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
