# Generated by Django 2.0.2 on 2018-07-10 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mibandapp', '0010_remove_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mibandapp.Cart'),
            preserve_default=False,
        ),
    ]
