# Generated by Django 2.0.2 on 2018-07-17 21:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mibandapp', '0013_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
