# Generated by Django 2.0.2 on 2018-07-17 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mibandapp', '0014_auto_20180717_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paid_date',
            new_name='transaction_date',
        ),
    ]
