# Generated by Django 2.0.2 on 2018-07-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibandapp', '0018_auto_20180718_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, to='mibandapp.Image'),
        ),
    ]
