# Generated by Django 2.0.2 on 2018-07-20 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mibandapp', '0023_auto_20180719_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=32)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibandapp.FeatureList')),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['is_deleted', '-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, to='mibandapp.ProductFeature'),
        ),
    ]
