# Generated by Django 2.0.2 on 2018-07-23 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mibandapp', '0025_auto_20180722_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeatureDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='image',
            name='is_thumbnail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productfeaturedetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibandapp.Product'),
        ),
    ]
