# Generated by Django 2.0.2 on 2018-07-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibandapp', '0027_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
