# Generated by Django 2.0.2 on 2018-07-27 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mibandapp', '0030_auto_20180727_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='shipping_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mibandapp.ShippingZone'),
        ),
    ]
