# Generated by Django 2.0.2 on 2018-07-27 16:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mibandapp', '0031_state_shipping_zone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['is_deleted', '-created_at'], 'permissions': (('can_add_product', 'Can add product'),)},
        ),
        migrations.AlterModelManagers(
            name='productslider',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
