# Generated by Django 2.0.2 on 2018-07-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mibandapp', '0032_auto_20180727_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': (('can_manage_order', 'Can manage orders'),)},
        ),
    ]
