# Generated by Django 2.0.2 on 2018-08-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibandapp', '0038_order_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingzone',
            name='additional_kg_cost',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=12),
            preserve_default=False,
        ),
    ]
