# Generated by Django 2.0.2 on 2018-08-22 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mibandapp', '0040_pushnotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushnotification',
            old_name='endpoint',
            new_name='subscription',
        ),
        migrations.RemoveField(
            model_name='pushnotification',
            name='auth',
        ),
        migrations.RemoveField(
            model_name='pushnotification',
            name='p256dh',
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
